name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 reportlab pypdf num2words pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --name "ChequePrinter" `
            --add-data "src/ui/cheque_writer.ui;src/ui" `
            --add-data "src/ui/check;src/ui" `
            main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: ChequePrinter v1.0.${{ github.run_number }}
          files: dist/ChequePrinter.exe